### ISSUE TITLE
Polyline drawing behavior a bit confusing.

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1441]
Not sure if this is an issue, but the following was reported on the polyline widget:
After placing the widget in the OPI user wishes to change line width. However, the polyline is still in edit mode, so clicking in the line width input field will create another point in the display area. This point is of course not visible as it obscured by the edit tools. Further, when the mouse is moved outside the visible display area to the line width input field, the cursor changes from the edit cursor (green plus sign) to an input cursor. Not possible to take screen shots, though.

If the above is not the intended behavior the I guess editing of the line should be "paused" or terminated when mouse is moved outside the visible display area.

A user also reports that occasionally it is in this scenario not possible to terminate polyline editing (using ESC). The following stack trace is dumped:

`2020-07-30 16:33:49 SEVERE [org.csstudio.display.builder.model] Unknown listener org.csstudio.display.builder.editor.poly.PointsBinding@1b5751d4
java.lang.Exception: Unknown listener
at org.csstudio.display.builder.model.properties.PropertyChangeHandler.removePropertyListener(PropertyChangeHandler.java:119)
at org.csstudio.display.builder.editor.poly.PointsBinding.disposeEditor(PointsBinding.java:126)
at org.csstudio.display.builder.editor.poly.PointsBinding.done(PointsBinding.java:228)
at org.csstudio.display.builder.editor.poly.PointsEditor.lambda$new$0(PointsEditor.java:101)
at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
at javafx.event.Event.fireEvent(Event.java:198)
at javafx.scene.Scene$KeyHandler.process(Scene.java:4098)
at javafx.scene.Scene.processKeyEvent(Scene.java:2157)
at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2625)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
at com.sun.glass.ui.View.notifyKey(View.java:971)
at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
at org.csstudio.display.builder.editor.poly.PointsEditor.endMode(PointsEditor.java:228)
at org.csstudio.display.builder.editor.poly.PointsEditor.dispose(PointsEditor.java:234)
at org.csstudio.display.builder.editor.poly.PointsBinding.disposeEditor(PointsBinding.java:127)
at org.csstudio.display.builder.editor.poly.PointsBinding.done(PointsBinding.java:228)
at org.csstudio.display.builder.editor.poly.PointsEditor.lambda$new$0(PointsEditor.java:101)
at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
at javafx.event.Event.fireEvent(Event.java:198)
at javafx.scene.Scene$KeyHandler.process(Scene.java:4098)
at javafx.scene.Scene.processKeyEvent(Scene.java:2157)
at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2625)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
at com.sun.glass.ui.View.notifyKey(View.java:971)
at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by georgweiss** [comment]
Thanks.
