### ISSUE TITLE
Set string value on waveform record over pva

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2397]
A user has configured a waveform record to hold a file name value, i.e. a string value. This "works" over ca: read/write works as expected from a TextUpdate widget.

Switching to pva a write operation from the widget fails:
```
java.lang.Exception: Cannot set byte[] value to test.txt
    at org.epics.pva.data.PVAByteArray.setValue(PVAByteArray.java:86)
    at org.epics.pva.client.PutRequest.encodeRequest(PutRequest.java:138)
    at org.epics.pva.common.TCPHandler.sender(TCPHandler.java:186)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Question is if PVAByteArray should also covert String values.

**Comment by kasemir** [comment]
> Question is if PVAByteArray should also support conversion of String values.

Yes.

We could contemplate if that it best implemented in the https://github.com/ControlSystemStudio/phoebus/tree/master/core/pv/src/main/java/org/phoebus/pv/pva layer that interfaces between core-pva and the VTypes, or directly in core-pva.

For channel access, we do it in the https://github.com/ControlSystemStudio/phoebus/blob/master/core/pv/src/main/java/org/phoebus/pv/ca/JCA_PV.java, that is the CA to VType interface layer.
But I suggest we do is directly in core-pva, that is in the https://github.com/ControlSystemStudio/phoebus/blob/master/core/pva/src/main/java/org/epics/pva/data/PVAByteArray.java that you mention.
So add that to org.epics.pva.data.PVAByteArray.setValue, converting the string to bytes similar to what's in JCA_PV.performWrite.
