### ISSUE TITLE
Configuring Alarm Logger with Phoebus

### ISSUE THREAD

**Issue by UrbanBobek** [ControlSystemStudio/phoebus#2433]
Hi all,

I am trying to configure Alarm Logger, but I am currently stuck. 
I have Elasticsearch (version 6.8.1) running in a docker container. Running ```curl -XGET http://my_elastic:9200``` returns the following:
```root@ubobek: /# curl -X GET localhost:9200
{
  "name" : "epics-services-1",
  "cluster_name" : "epics-services",
  "cluster_uuid" : "IbfvxgBKQOWwxGq4PRU-5Q",
  "version" : {
    "number" : "6.8.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "1fad4e1",
    "build_date" : "2019-06-18T13:16:52.517138Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
On the same host in a different container I am running Alarm Server and Alarm Logger (versions 4.6.0) along side Kafka and Zookeeper. I was able to get Alarm Server working, but not Alarm Logger. Prior to starting Alarm Logger I ran ``` bash create_alarm_templates.sh```. I start Alarm Logger with ```bash alarm-logger.sh -es_host localhost -es_port 9200 ``` and get the following response:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/opt/alarm-logger-4.6.0/lib/spring-core-5.0.9.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] Alarm Logging Service (PID 1459)
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] Properties:
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] es_port:9200
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] date_span_value:1
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] es_host:localhost
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] alarm_topics:Accelerator
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] bootstrap.servers:localhost:9092
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] es_sniff:false
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] date_span_units:M
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] es_max_size:1000
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] Starting logger for '..State': [Accelerator]
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] Starting the alarm messages stream consumer for Accelerator
2022-10-28 14:28:55 INFO [org.phoebus.alarm.logging] Starting the cmd stream consumer for Accelerator
Commands:
        help             - Show help.
        shutdown         - Shut alarm logger down and exit.

 > 2022-10-28 14:28:55.581  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.583  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.583  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.584  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.584  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.579  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.585  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.587  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.587  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.589  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.590  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.590  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.591  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.591  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.admin.AdminClientConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.679  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.679  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.679  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.679  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.681  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.681  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.679  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.681  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.711  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.713  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.712  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.714  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.714  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.716  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.811  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.811  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.812  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.813  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.813  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.814  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.815  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.820  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.821  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.producer.ProducerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.838  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.842  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.842  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.842  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.842  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.843  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'admin.retries' was supplied but isn't a known config.
2022-10-28 14:28:55.843  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.843  WARN 1459 --- [pool-1-thread-1] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
2022-10-28 14:28:55.850  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_max_size' was supplied but isn't a known config.
2022-10-28 14:28:55.852  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_value' was supplied but isn't a known config.
2022-10-28 14:28:55.853  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_host' was supplied but isn't a known config.
2022-10-28 14:28:55.855  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'date_span_units' was supplied but isn't a known config.
2022-10-28 14:28:55.856  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_port' was supplied but isn't a known config.
2022-10-28 14:28:55.857  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'admin.retries' was supplied but isn't a known config.
2022-10-28 14:28:55.858  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'alarm_topics' was supplied but isn't a known config.
2022-10-28 14:28:55.858  WARN 1459 --- [pool-1-thread-2] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'es_sniff' was supplied but isn't a known config.
```
I should note that the command ```curl -XGET http://localhost:9200``` returns the same response in the Alarm container as on the host machine,

In Phoebus (CS Studio version: master 2022-10-05 03:51) in Alarm Log Table I do not get any logs, even if I set the query to '*'. My Phoebus settings are:
```
# Channel Access address list
org.phoebus.pv.ca/addr_list=localhost
org.phoebus.pv.ca/auto_addr_list=true
org.phoebus.pv.pva/epics_pva_addr_list=localhost
org.phoebus.pv.pva/epics_pva_auto_addr_list=true

# # Kafka Server host:port
org.phoebus.applications.alarm/server=localhost:9092

# # Name of alarm tree root
org.phoebus.applications.alarm/config_name=Accelerator
org.phoebus.applications.alarm/config_names=Accelerator

org.phoebus.applications.alarm.logging.ui/es_host=localhost
org.phoebus.applications.alarm.logging.ui/es_port=9200
org.phoebus.applications.alarm.logging.ui/es_index=accelerator_alarms
org.phoebus.applications.alarm.logging.ui/service_uri=http://localhost:9200

```
And the output after a query is
```
2022-10-28 15:04:22 INFO [org.phoebus.framework.jobs] Job 'searching alarm log messages for : *': searching for alarm log entires : current_severity:*message:*start:7 dayspv:*severity:*end:nowcommand:*current_message:*host:*user:* - Cancelled

2022-10-28 15:04:22 WARNING [org.phoebus.framework.jobs] Job 'searching alarm log messages for : *' failed

com.sun.jersey.api.client.UniformInterfaceException: GET http://localhost:9200/search/alarm?severity=*&current_message=*&current_severity=*&size=10000&pv=*&start=7+days&host=*&end=now&message=*&user=*&command=* returned a response status of 405 Method Not Allowed

	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)

	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)

	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)

	at org.phoebus.applications.alarm.logging.ui.AlarmLogSearchJob.run(AlarmLogSearchJob.java:83)

	at org.phoebus.framework.jobs.Job.execute(Job.java:50)

	at org.phoebus.framework.jobs.JobManager.execute(JobManager.java:54)

	at org.phoebus.framework.jobs.JobManager.lambda$schedule$0(JobManager.java:45)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:829)


```
I am able to query some logs from elastic search with:
```
user@ubobek: /$ curl -X GET 'http://localhost:9200/accelerator_alarms_state*/_search?format=json&pretty'
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 37676,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "accelerator_alarms_state_2022-09-30",
        "_type" : "alarm",
        "_id" : "7CNyGYQBW1jdn5_Tt4gy",
        "_score" : 1.0,
        "_source" : {
          "severity" : "MAJOR",
          "current_message" : "HIGH_ALARM",
          "mode" : null,
          "message_time" : "2022-10-27 12:37:39.192",
          "current_severity" : "MINOR",
          "pv" : "ubobek:calcExample",
          "latch" : "false",
          "time" : "2022-10-27 12:33:31.192",
          "message" : "HIHI_ALARM",
          "config" : "state:/Accelerator/testComponent1/ubobek:calcExample",
          "value" : "8.0"
        }
      },
      {
        "_index" : "accelerator_alarms_state_2022-09-30",
        "_type" : "alarm",
        "_id" : "7SNyGYQBW1jdn5_Tt4hE",
        "_score" : 1.0,
        "_source" : {
          "severity" : "MINOR",
          "current_message" : "LOW_ALARM",
          "mode" : null,
          "message_time" : "2022-10-27 12:37:39.192",
          "current_severity" : "MINOR",
          "pv" : "ubobek:calcExample2",
          "latch" : "false",
          "time" : "2022-10-27 12:37:39.192",
          "message" : "LOW_ALARM",
          "config" : "state:/Accelerator/testComponent2/ubobek:calcExample2",
          "value" : "3.0"
        }
      },
 . . .
```
Looking at the output I also noticed that none of the messages are from my testing today (2022-10-28). I also expanded the start and end time as proposed in https://github.com/ControlSystemStudio/phoebus/issues/791 but without success.

In case it is relevant, here is also the elasticsearch.yml file:
```
cluster.name: "epics-services"
node.name: "epics-services-1"
network.host: ["_local:ipv4_", "_site:ipv4_"]
network.publish_host: "_local:ipv4_"
transport.port: "19300"
http.port: "9200"

# Snapshots
path.repo: ["/usr/share/elasticsearch/snapshots"]
```

Any help would be greatly appreciated!

**Comment by georgweiss** [comment]
Recently (#2332) we made a change in the service that also affects the Phoebus client:

- Service now requires Elasticsearch 8.x, e.g. 8.3.2
- Service now exposes a REST API, i.e. client need/should not access Elasticsearch.
- Client (Phoebus) now uses the REST API.

The URL to the REST API exposed by the service is configured like so:
```
org.phoebus.applications.alarm.logging.ui/service_uri=<URL>
```
The setting 
```
org.phoebus.applications.alarm.logging.ui/es_host
```
is obsolete and can be removed.

**Comment by UrbanBobek** [comment]
Thank you for the quick response!

I overlooked these changes, my apologies. I assume that I should also upgrade Alarm Logger to version 4.7.0 to work with these changes?

**Comment by georgweiss** [comment]
Exactly.

**Comment by georgweiss** [comment]
A very basic index migration option is described here: https://github.com/ControlSystemStudio/epics-codeathon-2022/discussions/5 (though for Channel Finder). It mentions Elasticsearch 7, but I've verified it works also with Elasticsearch as target.

**Comment by UrbanBobek** [comment]
Great, thank you for your help!
