### ISSUE TITLE
Tooltips for graphic widgets not showing up

### ISSUE THREAD

**Issue by tanviash** [ControlSystemStudio/phoebus#2878]
Tooltips for graphics widgets (label, arc, rectangle etc.) don't seem to show up anymore. But for other types of non-graphics widgets like monitors and controls, tooltips seem to work fine. I'm trying this on Linux Debian machine.

**Comment by kasemir** [comment]
In the log, you probably see something like this:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Widget 'Rectangle' (rectangle) has no 'pv_value' property
	at org.csstudio.display.builder.model.Widget.getProperty(Widget.java:598)
	at org.csstudio.display.builder.model.Widget.getProperty(Widget.java:563)
	at org.csstudio.display.builder.model.Widget.getPropertyValue(Widget.java:678)
	at org.csstudio.display.builder.representation.javafx.widgets.TooltipSupport.lambda$attach$0(TooltipSupport.java:100)
```

Part of the update to show alarm limits #2769 breaks tool tips on widgets that have no value.

**Comment by kasemir** [comment]
Here's the problem: https://github.com/ControlSystemStudio/phoebus/blob/724c7baf11679ae640c57e1b9bfca45cb5c24b24/app/display/representation-javafx/src/main/java/org/csstudio/display/builder/representation/javafx/widgets/TooltipSupport.java#L100

Needs to check if there is a value property
